In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("./Data_Download_ECHO.csv", index_col=None)

In [ ]:
#, parse_ids=['FacStreet']

In [4]:
df.head()

,FacName,FacStreet,FacCity,FacState,RegistryID,FacSNCFlg,FacQtrsWithNC,FacInspectionCount,FacFormalActionCount,FacMapFlg,SupOver80CountUsDisp,DFR URL
0,1127 CIGARETTE CORP,1127/45 FLUSHING AVE,BROOKLYN,NY,110019408933,N,0.0,0,0,Y,11.0,https://echo.epa.gov/detailed-facility-report?...
1,16 TONS INC,27 KNICKERBOCKER AVE,BROOKLYN,NY,110017761689,N,0.0,0,0,Y,12.0,https://echo.epa.gov/detailed-facility-report?...
2,1601 DEKALB AVENUE LLC,1601 DEKALB AVE,BROOKLYN,NY,NYR000266270,N,0.0,0,0,Y,NaN,https://echo.epa.gov/detailed-facility-report?...
3,194 HARMAN ST SCHOOL P-376A,194 HARMAN ST,BROOKLYN,NY,110043575379,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...
4,512 JOHNSON AVE BUILDING,512 JOHNSON AVE,BROOKLYN,NY,110038447071,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...

In [9]:
print(df.columns)

Index(['FacName', 'FacStreet', 'FacCity', 'FacState', 'RegistryID',
       'FacSNCFlg', 'FacQtrsWithNC', 'FacInspectionCount',
       'FacFormalActionCount', 'FacMapFlg', 'SupOver80CountUsDisp', 'DFR URL'],
      dtype='object')

In [23]:
column_df = df[['RegistryID']]
column_df

       RegistryID
0    110019408933
1    110017761689
2    NYR000266270
3    110043575379
4    110038447071
..            ...
126  110040090772
127  110004433104
128  110000810891
129  110004364875
130  110043220699

[131 rows x 1 columns]

In [10]:
df.dtypes

FacName                  object
FacStreet                object
FacCity                  object
FacState                 object
RegistryID               object
FacSNCFlg                object
FacQtrsWithNC           float64
FacInspectionCount        int64
FacFormalActionCount      int64
FacMapFlg                object
SupOver80CountUsDisp    float64
DFR URL                  object
dtype: object

## Prompt

Imagine you want to send the above analytics information (that came from somewhere like your internal Google Analytics platform) to ChatGPT to be analyzed to spot trends and forecast traffic.

1. What PII is in here that needs to be protected?
2. How could you mask that PII so that this data could be passed to ChatGPT?

*Fun fact:* ChatGPT generated most of this CSV, but it forgot to enclose the `Location` field in quotes, which threw me off for a long time.

In [26]:
#df['id'] = df['RegistryID'].apply(lambda x: 123456789123 - x.year)
#df['id'] = df['RegistryID'].apply(lambda x: '*' * (len(str(x)) - 4) + str(x)[-4:])
mask_id = df['RegistryID'] = df['RegistryID'].apply(lambda x: '***' + str(x)[3:]) #First 3 Digits as Stars

In [27]:
df.head()

,FacName,FacStreet,FacCity,FacState,RegistryID,FacSNCFlg,FacQtrsWithNC,FacInspectionCount,FacFormalActionCount,FacMapFlg,SupOver80CountUsDisp,DFR URL,id
0,1127 CIGARETTE CORP,1127/45 FLUSHING AVE,BROOKLYN,NY,***019408933,N,0.0,0,0,Y,11.0,https://echo.epa.gov/detailed-facility-report?...,***019408933
1,16 TONS INC,27 KNICKERBOCKER AVE,BROOKLYN,NY,***017761689,N,0.0,0,0,Y,12.0,https://echo.epa.gov/detailed-facility-report?...,***017761689
2,1601 DEKALB AVENUE LLC,1601 DEKALB AVE,BROOKLYN,NY,***000266270,N,0.0,0,0,Y,NaN,https://echo.epa.gov/detailed-facility-report?...,***000266270
3,194 HARMAN ST SCHOOL P-376A,194 HARMAN ST,BROOKLYN,NY,***043575379,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***043575379
4,512 JOHNSON AVE BUILDING,512 JOHNSON AVE,BROOKLYN,NY,***038447071,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***038447071

In [29]:
df['FacStreet'] = df['FacStreet'].apply(
    lambda x: x[0] + '*' * (len(x) - 2) + x[-1] if len(x) > 1 else '*'
)

df

,FacName,FacStreet,FacCity,FacState,RegistryID,FacSNCFlg,FacQtrsWithNC,FacInspectionCount,FacFormalActionCount,FacMapFlg,SupOver80CountUsDisp,DFR URL,id
0,1127 CIGARETTE CORP,1******************E,BROOKLYN,NY,***019408933,N,0.0,0,0,Y,11.0,https://echo.epa.gov/detailed-facility-report?...,***019408933
1,16 TONS INC,2******************E,BROOKLYN,NY,***017761689,N,0.0,0,0,Y,12.0,https://echo.epa.gov/detailed-facility-report?...,***017761689
2,1601 DEKALB AVENUE LLC,1*************E,BROOKLYN,NY,***000266270,N,0.0,0,0,Y,NaN,https://echo.epa.gov/detailed-facility-report?...,***000266270
3,194 HARMAN ST SCHOOL P-376A,1***********T,BROOKLYN,NY,***043575379,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***043575379
4,512 JOHNSON AVE BUILDING,5*************E,BROOKLYN,NY,***038447071,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***038447071
...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,WASTE MANAGEMENT OF NY LLC,2************E,BROOKLYN,NY,***040090772,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***040090772
127,WASTE MANAGEMENT OF NY-123 VARICK AVE,1***************E,BROOKLYN,NY,***004433104,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***004433104
128,WILCO FINISHING CORP,1********************E,BROOKLYN,NY,***000810891,Y,12.0,0,0,Y,11.0,https://echo.epa.gov/detailed-facility-report?...,***000810891
129,WYCKOFF HEIGHTS MEDICAL CENTER,3**************T,BROOKLYN,NY,***004364875,N,0.0,2,0,Y,10.0,https://echo.epa.gov/detailed-facility-report?...,***004364875
130,YANG'S IMPORT INC,1***************E,BROOKLYN,NY,***043220699,N,0.0,0,0,Y,12.0,https://echo.epa.gov/detailed-facility-report?...,***043220699

In [30]:
df['FacName'] = df['FacName'].apply(
    lambda x: x[0] + '*' * (len(x) - 2) + x[-1] if len(x) > 1 else '*'
)

df

,FacName,FacStreet,FacCity,FacState,RegistryID,FacSNCFlg,FacQtrsWithNC,FacInspectionCount,FacFormalActionCount,FacMapFlg,SupOver80CountUsDisp,DFR URL,id
0,1*****************P,1******************E,BROOKLYN,NY,***019408933,N,0.0,0,0,Y,11.0,https://echo.epa.gov/detailed-facility-report?...,***019408933
1,1*********C,2******************E,BROOKLYN,NY,***017761689,N,0.0,0,0,Y,12.0,https://echo.epa.gov/detailed-facility-report?...,***017761689
2,1********************C,1*************E,BROOKLYN,NY,***000266270,N,0.0,0,0,Y,NaN,https://echo.epa.gov/detailed-facility-report?...,***000266270
3,1*************************A,1***********T,BROOKLYN,NY,***043575379,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***043575379
4,5**********************G,5*************E,BROOKLYN,NY,***038447071,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***038447071
...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,W************************C,2************E,BROOKLYN,NY,***040090772,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***040090772
127,W***********************************E,1***************E,BROOKLYN,NY,***004433104,N,0.0,0,0,Y,0.0,https://echo.epa.gov/detailed-facility-report?...,***004433104
128,W******************P,1********************E,BROOKLYN,NY,***000810891,Y,12.0,0,0,Y,11.0,https://echo.epa.gov/detailed-facility-report?...,***000810891
129,W****************************R,3**************T,BROOKLYN,NY,***004364875,N,0.0,2,0,Y,10.0,https://echo.epa.gov/detailed-facility-report?...,***004364875
130,Y***************C,1***************E,BROOKLYN,NY,***043220699,N,0.0,0,0,Y,12.0,https://echo.epa.gov/detailed-facility-report?...,***043220699

In [31]:
df['DFR URL'] = df['DFR URL'].apply(
    lambda x: x.split('/')[0] + '//' + x.split('/')[2] + '/****' if '//' in x else '****'
)

df

,FacName,FacStreet,FacCity,FacState,RegistryID,FacSNCFlg,FacQtrsWithNC,FacInspectionCount,FacFormalActionCount,FacMapFlg,SupOver80CountUsDisp,DFR URL,id
0,1*****************P,1******************E,BROOKLYN,NY,***019408933,N,0.0,0,0,Y,11.0,https://echo.epa.gov/****,***019408933
1,1*********C,2******************E,BROOKLYN,NY,***017761689,N,0.0,0,0,Y,12.0,https://echo.epa.gov/****,***017761689
2,1********************C,1*************E,BROOKLYN,NY,***000266270,N,0.0,0,0,Y,NaN,https://echo.epa.gov/****,***000266270
3,1*************************A,1***********T,BROOKLYN,NY,***043575379,N,0.0,0,0,Y,0.0,https://echo.epa.gov/****,***043575379
4,5**********************G,5*************E,BROOKLYN,NY,***038447071,N,0.0,0,0,Y,0.0,https://echo.epa.gov/****,***038447071
...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,W************************C,2************E,BROOKLYN,NY,***040090772,N,0.0,0,0,Y,0.0,https://echo.epa.gov/****,***040090772
127,W***********************************E,1***************E,BROOKLYN,NY,***004433104,N,0.0,0,0,Y,0.0,https://echo.epa.gov/****,***004433104
128,W******************P,1********************E,BROOKLYN,NY,***000810891,Y,12.0,0,0,Y,11.0,https://echo.epa.gov/****,***000810891
129,W****************************R,3**************T,BROOKLYN,NY,***004364875,N,0.0,2,0,Y,10.0,https://echo.epa.gov/****,***004364875
130,Y***************C,1***************E,BROOKLYN,NY,***043220699,N,0.0,0,0,Y,12.0,https://echo.epa.gov/****,***043220699

In [32]:
city_to_code = {
    "NY": 0,
    "Brooklyn": 1,
    
}

In [34]:
df['FacCity'] = df['FacCity'].apply(lambda x: city_to_code.get(x))

In [35]:
pii_columns = ['FacName', 'FacStreet', 'FacCity']

In [36]:
columns_to_use = [ c for c in df.columns if c not in pii_columns ]

In [37]:
df_clean = df[columns_to_use].copy()

In [38]:
df_clean.head()

,FacState,RegistryID,FacSNCFlg,FacQtrsWithNC,FacInspectionCount,FacFormalActionCount,FacMapFlg,SupOver80CountUsDisp,DFR URL,id
0,NY,***019408933,N,0.0,0,0,Y,11.0,https://echo.epa.gov/****,***019408933
1,NY,***017761689,N,0.0,0,0,Y,12.0,https://echo.epa.gov/****,***017761689
2,NY,***000266270,N,0.0,0,0,Y,NaN,https://echo.epa.gov/****,***000266270
3,NY,***043575379,N,0.0,0,0,Y,0.0,https://echo.epa.gov/****,***043575379
4,NY,***038447071,N,0.0,0,0,Y,0.0,https://echo.epa.gov/****,***038447071

In [39]:
df_clean.to_csv('./masked_data.csv')